apiVersion: apps/v1
kind: Deployment
metadata:
  name: beekeeper
  labels:
  {{- include "beekeeper-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.beekeeper.replicas }}
  selector:
    matchLabels:
      app: beekeeper
    {{- include "beekeeper-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: beekeeper
      {{- include "beekeeper-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.beekeeper.beekeeper.image.repository }}:{{ .Values.beekeeper.beekeeper.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.beekeeper.beekeeper.imagePullPolicy }}
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3
        name: beekeeper
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
        resources: {{- toYaml .Values.beekeeper.beekeeper.resources | nindent 10 }}