apiVersion: v1
kind: Service
metadata:
  name: beekeeper-service
  labels:
  {{- include "beekeeper-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: beekeeper
    {{- include "beekeeper-api.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.service.ports | toYaml | nindent 2 }}